Initial version.
knaw-huc/review-component-react pull request #1
Opened 2024-02-15 08:08 UTC by ekoi

2024-02-15 09:05 UTC, kerim1 requested changes
Just some small comments and then it is ready to merge.

2024-02-15 09:05 UTC, kerim1 commented on src/StarRating.tsx
> +  page_id: string
These properties are not used in the component. So guessing they can be removed?

2024-02-15 09:05 UTC, kerim1 commented on src/StarRating.tsx
> +    <div>
Is the wrapper `<div>` required?

2024-02-15 09:05 UTC, kerim1 commented on src/review.tsx
> +  }
Function is not used, so can be removed.

2024-02-15 09:05 UTC, kerim1 commented on src/review.tsx
> +    handleRating: any
The type for `handleRating` is not defined (is `any` now). Should be something like `(stars: number, reviewText: string) => void`.

2024-02-15 09:05 UTC, kerim1 commented on src/review.tsx
> +        <Form.Root
Can you give this a `classname` attribute? Something like `className="reviewForm"`? That makes the styling easier for someone using this component.

2024-03-21 08:22 UTC, ekoi commented on src/review.tsx
> +        <Form.Root
Done

2024-03-21 09:20 UTC, kerim1 commented on src/StarRating.tsx
> +  page_id: string
They are still there?

2024-03-21 09:23 UTC, kerim1 requested changes

2024-03-21 09:23 UTC, kerim1 commented on src/review.tsx
> +        <Form.Root
I meant the `Form.Root`

2024-03-21 09:24 UTC, kerim1 commented on src/review.tsx
> +  }
Is still there?

2024-03-21 09:25 UTC, merged